[package]
name = "server"
version = "0.1.0"
authors = ["DevOrc <ncharlton002@gmail.com>"]
edition = "2018"


[dependencies]
warp = "0.1.14"
pretty_env_logger = "0.3"
futures = "0.1.26"
lib = {path="../lib"}
